### ISSUE TITLE
Commonjs

### ISSUE THREAD

**Issue by antal-k** [CSMTools/node-cs2-cdn#1]
Sadly this repo doesn't work with commonJS as the examples show

`const cs2CDN = require('cs2-cdn');`

**Comment by wavpro** [comment]
Will look into this, on vacation ATM but the coding addiction is too strong so I'll probably do something about this very soon!

**Comment by wavpro** [comment]
Sorry for the delay, but it's fixed now.

Only caveat is that on commonjs, it imports the class as the property `default`, so you need to do something like 
````js
require('cs2-cdn').default
